#!/usr/bin/env bash
# Build the AI-native Kali ISO (Phase 4 scaffold).
#
# Not runnable end to end yet: it needs a Debian/Kali host with live-build and
# root, and the metapackages are still v0.1.0 skeletons. It exists so the
# pipeline in blueprint section 07 is a real script rather than a diagram.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="${BUILD_DIR:-/tmp/ai-native-kali-build}"

if ! command -v lb >/dev/null 2>&1; then
  echo "live-build ('lb') is not installed: apt-get install live-build" >&2
  exit 1
fi

if [ "$(id -u)" -ne 0 ]; then
  echo "building an ISO requires root" >&2
  exit 1
fi

# --- preflight (Phase 16) ---------------------------------------------------
# Every blocker this build hit in the sandbox wasted a long run before it was
# found. State the requirements up front instead: the toolchain must be present,
# and BUILD_DIR's filesystem must have room for the chroot *and* the squashfs
# *and* the ISO. A cramped overlay failed at 7.8 GB / 8.0 GB with ENOSPC after
# ~40 minutes; the same failure is one `df` away from being knowable at t=0.
need_free_gb="${AI_MIN_FREE_GB:-15}"
for tool in lb xorriso mksquashfs debootstrap; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "required tool '$tool' is not installed" >&2
    exit 1
  fi
done
mkdir -p "$BUILD_DIR"
avail_kb="$(df -Pk "$BUILD_DIR" | awk 'NR==2 {print $4}')"
avail_gb="$((avail_kb / 1024 / 1024))"
echo "== preflight: $avail_gb GB free on $BUILD_DIR (need >= ${need_free_gb} GB)"
if [ "$avail_gb" -lt "$need_free_gb" ]; then
  echo "BUILD_DIR has ${avail_gb} GB free; the chroot + squashfs + ISO need ~${need_free_gb} GB." >&2
  echo "Point BUILD_DIR at a larger filesystem: BUILD_DIR=/var/lib/docker/ai-native-kali-build make iso-full" >&2
  exit 1
fi

echo "== staging $BUILD_DIR"
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"
cp -r "$ROOT/packaging/live-build/auto" "$BUILD_DIR/auto"
cp -r "$ROOT/packaging/live-build/config" "$BUILD_DIR/config"

# --- minimal package set (Phase 16 workaround) ------------------------------
# The chroot stage unpacks the full set (~2766 packages) and OOM-killed
# ``dpkg-deb`` twice in this sandbox, where the cgroup is hard-capped at 2 GB
# (``/sys/fs/cgroup/memory.max``; ``memory.events`` shows ``oom_kill 1``).
# Disk was never the constraint there - /var/lib/docker has 2.2 TB free. Dropping
# the heavy ``kali-tools-*`` bundles leaves the AI-native substrate installable
# inside that memory budget, so the pipeline can still be exercised end to end.
#
# This is a *build-verification* variant, not the release image: without the tool
# bundles and the webkit GTK stack the image lacks the tool set and the panel
# webview. The full set is what the release is meant to carry, so this is only
# written when AI_ISO_MINIMAL=1 is set - and it says so loudly.
if [ "${AI_ISO_MINIMAL:-0}" = "1" ]; then
  echo "== WARNING: AI_ISO_MINIMAL=1 - building the REDUCED package set."
  echo "   The image will NOT contain the kali-tools-* bundles or the webkit GTK stack."
  cat > "$BUILD_DIR/config/package-lists/kali-ai-native.list.chroot" <<'PKGLIST'
# AI-native Kali: MINIMAL chroot package list (AI_ISO_MINIMAL=1).
#
# Generated by packaging/build-iso.sh. This is the reduced set used to exercise
# the live-build pipeline where the chroot cannot unpack the full package set
# inside the available memory budget. It is NOT the release package set.
kali-linux-core
wayland-protocols
weston
xwayland
fonts-jetbrains-mono
python3
python3-venv
python3-pip
sqlite3
nodejs
npm
gir1.2-gtk-4.0
python3-gi
dbus-x11
PKGLIST
fi
mkdir -p "$BUILD_DIR/config/includes.chroot/opt/ai-native-kali"
cp -r "$ROOT/packaging/metapackages" "$BUILD_DIR/config/includes.chroot/opt/ai-native-kali/metapackages"
# `install -D` creates the parent directory; a bare `cp` into usr/bin fails
# because only opt/ai-native-kali exists at this point. That failure aborted the
# whole build before lb ever ran.
install -D -m 0755 "$ROOT/packaging/hermes-session/kali-ai-setup" \
  "$BUILD_DIR/config/includes.chroot/usr/bin/kali-ai-setup"

# The AI-native services themselves (source tree) go into the image.
for component in kanban-core tool-frontends agent-runtime observability hermes-shell; do
  mkdir -p "$BUILD_DIR/config/includes.chroot/opt/ai-native-kali/$component"
  cp -r "$ROOT/$component/"* "$BUILD_DIR/config/includes.chroot/opt/ai-native-kali/$component/"
done

# systemd units + session entry
install -D -m 0644 "$ROOT/packaging/hermes-session/kali-ai.target" \
  "$BUILD_DIR/config/includes.chroot/etc/systemd/system/kali-ai.target"
for unit in kali-ai-kanban.service kali-ai-observability.service hermes-shell.service; do
  install -D -m 0644 "$ROOT/packaging/hermes-session/$unit" \
    "$BUILD_DIR/config/includes.chroot/etc/systemd/system/$unit"
done
install -D -m 0644 "$ROOT/packaging/hermes-session/hermes-shell.desktop" \
  "$BUILD_DIR/config/includes.chroot/usr/share/wayland-sessions/hermes-shell.desktop"
# The session the .desktop Exec= line names. Without it the greeter offers a
# Hermes session that immediately dies back to the login screen.
install -D -m 0755 "$ROOT/packaging/hermes-session/hermes-shell-session" \
  "$BUILD_DIR/config/includes.chroot/usr/bin/hermes-shell-session"

# --- offline model bundle (Phase 8, item 3) --------------------------------
# The *config* half is staged here and is deterministic; the weights are staged
# by the build host with packaging/fetch_bundle.py and copied in if present. A
# build without the weights still produces a correct image that reports an empty
# bundle, rather than one that silently falls back and looks fine.
PROFILE="${AI_PROFILE:-minimal}"
BUNDLE_STAGE="${BUNDLE_STAGE:-/var/lib/kali-ai/models}"
echo "== staging model bundle config (profile: $PROFILE)"
mkdir -p "$BUILD_DIR/config/includes.chroot/opt/ai-native-kali/bundle"
python3 "$ROOT/packaging/fetch_bundle.py" manifest --profile "$PROFILE" \
  --out "$BUILD_DIR/config/includes.chroot/opt/ai-native-kali/bundle/manifest.json"
# The tooling travels with the image so a build host can re-verify what it staged.
install -D -m 0644 "$ROOT/packaging/profiles.py" \
  "$BUILD_DIR/config/includes.chroot/opt/ai-native-kali/bundle/profiles.py"
install -D -m 0755 "$ROOT/packaging/fetch_bundle.py" \
  "$BUILD_DIR/config/includes.chroot/opt/ai-native-kali/bundle/fetch_bundle.py"
if [ -d "$BUNDLE_STAGE" ] && [ -n "$(ls -A "$BUNDLE_STAGE" 2>/dev/null)" ]; then
  echo "  -> copying staged weights from $BUNDLE_STAGE"
  mkdir -p "$BUILD_DIR/config/includes.chroot/opt/hermes/models"
  cp -r "$BUNDLE_STAGE/." "$BUILD_DIR/config/includes.chroot/opt/hermes/models/"
else
  echo "  !! no weights staged at $BUNDLE_STAGE - image will report an empty bundle"
fi

cd "$BUILD_DIR"
echo "== lb config"
bash auto/config

# --- non-tty stages (Phase 16) ----------------------------------------------
# live-build only adds `-processors 1 -mem 256M` to mksquashfs when stdin is NOT
# a terminal; run from a terminal it uses every core ("Parallel mksquashfs: Using
# 64 processors" in the Phase 14 log) and is OOM-killed -- exit 137 -- inside a
# small cgroup. Redirecting stdin from /dev/null puts every stage on the
# conservative path, which is also what CI/cron get. Cheap insurance for a long
# build; harmless on a large host.
REDIRECT_STDIN=/dev/null

echo "== lb bootstrap"
lb bootstrap < "$REDIRECT_STDIN"
# In a container mknod is denied, so debootstrap cannot create real device
# nodes: chroot/dev/null ends up missing and any postinst that opens /dev/null
# fails -- e.g. the GVM/OpenVAS gpg key import aborts with
# "gpg: Fatal: failed to open '/dev/null': Permission denied", which then
# cascades to ospd-openvas/gvmd/gsad/gvm and fails the whole chroot stage.
# live-build mounts /proc, /sys and /dev/pts but never /dev. A whole-/dev bind
# does not survive lb's mount handling (verified: chroot/dev/null was still
# absent), so bind the individual device nodes the postinsts actually open.
# Harmless on a normal host, where the nodes already exist.
if [ -d "$BUILD_DIR/chroot/dev" ]; then
  for dev in null zero full random urandom tty; do
    if [ -e "/dev/$dev" ]; then
      touch "$BUILD_DIR/chroot/dev/$dev" 2>/dev/null || true
      mount --bind "/dev/$dev" "$BUILD_DIR/chroot/dev/$dev" 2>/dev/null || true
    fi
  done
fi
echo "== lb chroot (this is the long one)"
lb chroot < "$REDIRECT_STDIN"
echo "== lb binary"
lb binary < "$REDIRECT_STDIN"

# --- release artifact -------------------------------------------------------
# `--image-name` carries the *slug* (no spaces: live-build interpolates it into
# filenames unquoted - see auto/config), and the human release name is applied
# here as a rename, after every live-build stage has finished with the file.
BUILT_ISO="$BUILD_DIR/$RELEASE_NAME-amd64.hybrid.iso"
RELEASE_ISO="$BUILD_DIR/$RELEASE_FILENAME.iso"
echo "== done"
if [ -f "$BUILT_ISO" ]; then
  if [ "$BUILT_ISO" != "$RELEASE_ISO" ]; then
    mv -f "$BUILT_ISO" "$RELEASE_ISO"
  fi
  ls -l "$RELEASE_ISO"
  sha256sum "$RELEASE_ISO"
else
  echo "release image not found at: $BUILT_ISO" >&2
  ls -1 "$BUILD_DIR"/*.iso 2>/dev/null || echo 'no iso produced'
  exit 1
fi